title: Ukanwa Prisca Oluomachi
logo: IMG-20240912-WA0036.jpg



description: I am data scientist with a passion of helping organizations 
             in decision-making, which enhances business growth,
             with the help of disciplines like statistics and machine learning
             I can extract meaningful insights from data

theme: jekyll-theme-minimal

