title: Ukanwa Prisca Oluomachi
logo: /IMG-20240912-WA0036.jpg
description: I am data scientist with a passion of helping organizations 
in decision-making, which enhances business growth, I leverage on minimizing 
risks and with the help of disciplines like statistics and machine learning,
I can extract meaningful insights from data and empowers businesses
to maintain a competitive edge in their respective markets
show_download: true
theme: jekyll-theme-cayman
show_image: true
