title: Ukanwa Prisca Oluomachi
logo: IMG-20240912-WA0036.jpg



description: Data scientist passionate in helping organizations 
             in decision-making, which enhances business growth
            
theme: jekyll-theme-minimal

